### ISSUE TITLE
Unable to create an image

### ISSUE THREAD

**Issue by eladrave** [simonsanvil/GTP3-whatsapp-chatbot#11]
Hi,

Whenever I try to create an image, I get:
<img width="525" alt="Screen Shot 2023-03-07 at 9 57 27 PM" src="https://user-images.githubusercontent.com/86946294/223631390-49a87d64-740a-4f68-b9c7-e45af2223afb.png">

**Comment by simonsanvil** [comment]
Yeah, I've encountered the same problem when using chatgpt instead of davinci for answering messages. Chat-GPT was fine-tuned for only text-based assistance, so it heavily leans on that, even when the system message says otherwise. I've managed to improve it using different prompts for the start template. When I get the time, I'll add a few more of these templates so that users can test the ones that work best for them.

I'll close this issue in the meantime but feel free to re-open it if you want to add something more
